# Basic Site Settings
title                    : "Tianhao Luo"
name                     : &name "Tianhao Luo"
description              : &description "Incoming PhD student at Harvard in Biomedical AI"
url                      : https://JSluo888.github.io
repository               : "JSluo888/JSluo888.github.io"

# Site Author
author:
  avatar           : "profile.png"  # Be sure to place your profile picture in the images/ folder
  name             : "Tianhao Luo"
  pronouns         : "he/him"
  bio              : "Incoming PhD student in Biomedical Informatics (BIG Track) at Harvard Medical School. Passionate about multimodal, biomedical AI."
  location         : "Rancho Palos Verdes, CA"
  employer         : "Harvard Medical School"
  uri              : 
  email            : "luo.tianhao@outlook.com"

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=a0f8pt4AAAAJ&hl=en"
  orcid            : "https://orcid.org/0009-0005-3906-6669"
  pubmed           : ""

  # Repositories and software development
  github           : "JSluo888"

  # Social media
  linkedin         : "luo-tianhao"
  bluesky          : "bsky.app"

# Social Sharing
social:
  type             : "Person"
  name             : "Tianhao Luo"
  links:
    - "https://linkedin.com/in/luo-tianhao/"
    - "https://scholar.google.com/citations?user=a0f8pt4AAAAJ&hl=en"
    - "mailto:luo.tianhao@outlook.com"
